#!/bin/bash
source /usr/share/yunohost/helpers
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/_common.sh"

ynh_backup "$install_dir" "apps/$app"
ynh_backup "$data_dir" "apps/$app-data"
