#!/bin/bash
source /usr/share/yunohost/helpers
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$script_dir/_common.sh"

systemctl stop "$app" || true
ynh_remove_systemd_config
ynh_remove_nginx_config
